quadrantChart
    title Reach and engagement of Sudoku games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game": [0.3, 0.6]
    "Sudoku Free": [0.45, 0.23]
    "Sudoku.com": [0.57, 0.69]
    "Sudoku Solver": [0.78, 0.34]
    "Sudoku Village": [0.40, 0.34]
    "Sudoku Master": [0.35, 0.78]
    "Sudoku Genius": [0.6, 0.7]
    "Our Target Product": [0.5, 0.6]
